/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-03-23 23:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _005fSidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<nav id=\"page-leftbar\" role=\"navigation\">\r\n");
      out.write("                <!-- BEGIN SIDEBAR MENU -->\r\n");
      out.write("            <ul class=\"acc-menu\" id=\"sidebar\">\r\n");
      out.write("                <div><img class=\"logo\" src=\"assets/img/BPS_LOGO.png\" title=\"Business Productivity Solution\"></div>\r\n");
      out.write("                <li id=\"search\">\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa fa-search opacity-control\"></i></a>\r\n");
      out.write("                     <form>\r\n");
      out.write("                        <!--input type=\"text\" class=\"search-query\" placeholder=\"Search...\">\r\n");
      out.write("                        <button type=\"submit\"><i class=\"fa fa-search\"></i></button-->\r\n");
      out.write("                    </form>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"Dashboard\"><i class=\"fa fa-home\"></i> <span>Dashboard</span></a></li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-cog\"></i> <span>Configuration Management</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserManagement\">User Management</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ApprovingOfficer\">Approving Officer</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"CompanyPolicy\">Company Policy</a></li>\r\n");
      out.write("\t\t\t\t\t <li><a href=\"Currency\">Currency</a></li>\r\n");
      out.write("\t\t\t\t\t <li><a href=\"C-Destination.jsp\">Destination</a></li>\r\n");
      out.write("\t\t\t\t\t <li><a href=\"CardInformation\">Credit Card</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"C-Systemlog.jsp\">System Logs</a></li>\r\n");
      out.write("\t\t\t\t\t<!--li><a href=\"C-Import.jsp\">Import</a></li-->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-wrench\"></i> <span>Data-Builder</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Employee</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"EmployeeInformation\">Employee Information</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"EmployeeEmergencyContact\">Emergency Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"EmployeePassport\">Passport</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Department\">Department</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Position\">Position</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ServiceProvider\">Service Provider</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"S-Services.jsp\">Services</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-pencil-square-o\"></i> <span>Transaction</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelOrder\">Travel Order</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"CashAdvance\">Cash Advance</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelPlan\">Travel Plan</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelExpense\">Travel Expense</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"SupportDocument\">Support Document</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-list\"></i> <span>Query</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Userlist.jsp\">User List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Employoeelist.jsp\">Employee List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Approvingofficerlist.jsp\">Approving Officer List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Departmentlist.jsp\">Department List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Serviceproviderlist.jsp\">ServiceProvider List</a></li>\r\n");
      out.write("\t\t\t\t\t<!--li><a href=\"Q-Serviceslist.jsp\">Services List</a></li-->\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Hotellist.jsp\">Hotel List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Airlinelist.jsp\">Airline List</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Q-Carrentallist.jsp\">Car Rental List</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-book\"></i> <span>Report</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("                        <li><a href=\"TravelOrderReport\">Travel Order Report</a></li>\r\n");
      out.write("                        <li><a href=\"CashAdvanceReport\">Travel CashAdvance Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelPlanReport\">Travel Plan Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelExpenseReport\">Travel Expense Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelBudgetReport\">Travel Budget Report</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Travel Analytical Report</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"R-Expenseanalytical.jsp\">Expense Analytical Report</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"R-Travelanalytical.jsp\">Travel Analytical Report</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"Messages.jsp\"><i class=\"fa fa-envelope\"></i><span>Messages</span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- END SIDEBAR MENU -->\r\n");
      out.write("        </nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
