/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-08-07 15:34:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class R_002dTravelplanOfficer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/_Footer.jsp", Long.valueOf(1466779375425L));
    _jspx_dependants.put("/_SidebarOfficer.jsp", Long.valueOf(1459725316438L));
    _jspx_dependants.put("/_Topbar.jsp", Long.valueOf(1459347353879L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Report-Travel Plan</title>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"Avant\">\r\n");
      out.write("    <meta name=\"author\" content=\"The Red Team\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.min.css\">\r\n");
      out.write("    <link href='assets/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='styleswitcher'> \r\n");
      out.write("    <link href='assets/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='headerswitcher'> \r\n");
      out.write("    \r\n");
      out.write("    <link rel='stylesheet' type='text/css' href='assets/plugins/codeprettifier/prettify.css' /> \r\n");
      out.write("    <link rel='stylesheet' type='text/css' href='assets/plugins/form-toggle/toggles.css' />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/plugins/datatables/dataTables.css\">\r\n");
      out.write("    <link rel='stylesheet' type='text/css' href='assets/fonts/glyphicons/css/glyphicons.min.css' />\r\n");
      out.write("    <link rel='stylesheet' type='text/css' href='assets/css/custom.css'/>\r\n");
      out.write("<link rel='shortcut icon' href='assets/img/BPS_LOGO.png' type='image/jpeg' style=\"width: 16px; height: 16px;\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\" \">\r\n");
      out.write("\r\n");
      out.write("<!--BEGIN HEADERBAR poping header-->\r\n");
      out.write("<!--END HEADERBAR poping header-->\r\n");
      out.write("<!--BEGIN TOPBAR-->\r\n");
      out.write("<header class=\"navbar navbar-inverse navbar-fixed-top\" role=\"banner\">\r\n");
      out.write("        <a id=\"leftmenu-trigger\" class=\"tooltips\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Toggle Sidebar\"></a>\r\n");
      out.write("        <!--a id=\"rightmenu-trigger\" class=\"tooltips\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Toggle Infobar\">\r\n");
      out.write("        RIGHT BAR NAV\r\n");
      out.write("        </a-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header pull-left\" style=\"margin-top:10px;\">\r\n");
      out.write("             <span style=\"font-size:18px; color:white;\" >&nbsp;BPS - PTMS</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav navbar-nav pull-right toolbar\">\r\n");
      out.write("        \t<li class=\"dropdown\">\r\n");
      out.write("        \t\t<a href=\"#\" class=\"dropdown-toggle username\" data-toggle=\"dropdown\"><span class=\"hidden-xs\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.employee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <i class=\"fa fa-caret-down\"></i></span><img src=\"assets/demo/avatar/dangerfield.png\" alt=\"Dangerfield\" /></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu userinfo arrow\">\r\n");
      out.write("        \t\t\t<li class=\"username\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("        \t\t\t\t    <div class=\"pull-left\"><img class=\"userimg\" src=\"assets/demo/avatar/dangerfield.png\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.employee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/></div>\r\n");
      out.write("        \t\t\t\t    <div class=\"pull-right\"><h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.employee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h5><small>Logged in as <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></small></div>\r\n");
      out.write("                        </a>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t\t<li class=\"userlinks\">\r\n");
      out.write("        \t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("        \t\t\t\t\t<!--li><a href=\"#\">Account <i class=\"pull-right fa fa-cog\"></i></a></li>\r\n");
      out.write("        \t\t\t\t\t<li><a href=\"#\">Help <i class=\"pull-right fa fa-question-circle\"></i></a></li>\r\n");
      out.write("        \t\t\t\t\t<li class=\"divider\"></li-->\r\n");
      out.write("        \t\t\t\t\t<li><a href=\"Authentication?logout=logout\" class=\"text-right\">Sign Out</a></li>\r\n");
      out.write("        \t\t\t\t</ul>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t</li>\r\n");
      out.write("        \t<!--li class=\"dropdown\">\r\n");
      out.write("        \t\t<a href=\"#\" class=\"hasnotifications dropdown-toggle\" data-toggle='dropdown'><i class=\"fa fa-envelope\"></i><span class=\"badge\">1</span></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu messages arrow\">\r\n");
      out.write("        \t\t\t<li class=\"dd-header\">\r\n");
      out.write("        \t\t\t\t<span>You have 1 new message(s)</span>\r\n");
      out.write("        \t\t\t\t<span><a href=\"#\">Mark all Read</a></span>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("                    <div class=\"scrollthis\">\r\n");
      out.write("    \t\t\t        <li><a href=\"#\" class=\"active\">\r\n");
      out.write("    \t\t\t        \t<span class=\"time\">6 mins</span>\r\n");
      out.write("    \t\t\t        \t<img src=\"assets/demo/avatar/doyle.png\" alt=\"avatar\" />\r\n");
      out.write("    \t\t\t        \t<div><span class=\"name\">Alan Doyle</span><span class=\"msg\">Please mail me the files by tonight.</span></div>\r\n");
      out.write("    \t\t\t        </a></li>\r\n");
      out.write("    \t\t\t        <li><a href=\"#\">\r\n");
      out.write("    \t\t\t        \t<span class=\"time\">12 mins</span>\r\n");
      out.write("    \t\t\t        \t<img src=\"assets/demo/avatar/paton.png\" alt=\"avatar\" />\r\n");
      out.write("    \t\t\t        \t<div><span class=\"name\">Polly Paton</span><span class=\"msg\">Uploaded all the files to server. Take a look.</span></div>\r\n");
      out.write("    \t\t\t        </a></li>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \t\t\t<li class=\"dd-footer\"><a href=\"Messages.jsp\">View All Messages</a></li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t</li-->\r\n");
      out.write("            <!--li><a href=\"#\" title=\"Email\"><i class=\"glyphicon glyphicon-send\"></i></a></li-->\r\n");
      out.write("        \t<!--li class=\"dropdown\">\r\n");
      out.write("        \t\t<a href=\"#\" class=\"hasnotifications dropdown-toggle\" data-toggle='dropdown' id=\"woo\"><i class=\"fa fa-bell\"></i><span class=\"badge\">3</span></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu notifications arrow\" id=\"woo2\">\r\n");
      out.write("        \t\t\t<li class=\"dd-header\">\r\n");
      out.write("        \t\t\t\t<span>You have 3 new notification(s)</span>\r\n");
      out.write("        \t\t\t\t<span><a href=\"#\">Mark all Seen</a></span>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("                    <div class=\"scrollthis\">\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-user active\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">4 mins</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-user\"></i>\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">New user Registered. </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-danger active\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">20 mins</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-bolt\"></i>\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">CPU at 92% on server#3! </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-success active\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">1 hr</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-check\"></i> \r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">Server#1 is live. </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-warning\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">2 hrs</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-exclamation-triangle\"></i> \r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">Database overloaded. </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-order\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">10 hrs</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-shopping-cart\"></i> \r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">New order received. </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-failure\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">12 hrs</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-times-circle\"></i>\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">Application error!</span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-fix\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">12 hrs</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-wrench\"></i>\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">Installation Succeeded.</span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("    \t\t\t\t    <li>\r\n");
      out.write("    \t\t\t\t    \t<a href=\"#\" class=\"notification-success\">\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"time\">18 hrs</span>\r\n");
      out.write("    \t\t\t\t    \t\t<i class=\"fa fa-check\"></i>\r\n");
      out.write("    \t\t\t\t    \t\t<span class=\"msg\">Account Created. </span>\r\n");
      out.write("    \t\t\t\t    \t</a>\r\n");
      out.write("    \t\t\t\t    </li>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \t\t\t<li class=\"dd-footer\"><a href=\"#\">View All Notifications</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li-->\r\n");
      out.write("            <!--li> Header Dropdown\r\n");
      out.write("                <a href=\"#\" id=\"headerbardropdown\"><span><i class=\"fa fa-level-down\"></i></span></a>\r\n");
      out.write("            </li-->\r\n");
      out.write("            <li class=\"dropdown demodrop\">\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle tooltips\" data-toggle=\"dropdown\"><i class=\"fa fa-cogs\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"dropdown-menu arrow dropdown-menu-form\" id=\"demo-dropdown\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label for=\"demo-header-variations\" class=\"control-label\">Header Colors</label>\r\n");
      out.write("                        <ul class=\"list-inline demo-color-variation\" id=\"demo-header-variations\">\r\n");
      out.write("                            <li><a class=\"color-black\" href=\"javascript:;\"  data-headertheme=\"header-black.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-dark\" href=\"javascript:;\"  data-headertheme=\"default.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-red\" href=\"javascript:;\" data-headertheme=\"header-red.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-blue\" href=\"javascript:;\" data-headertheme=\"header-blue.css\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"divider\"></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label for=\"demo-color-variations\" class=\"control-label\">Sidebar Colors</label>\r\n");
      out.write("                        <ul class=\"list-inline demo-color-variation\" id=\"demo-color-variations\">\r\n");
      out.write("                            <li><a class=\"color-lite\" href=\"javascript:;\"  data-theme=\"default.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-steel\" href=\"javascript:;\" data-theme=\"sidebar-steel.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-lavender\" href=\"javascript:;\" data-theme=\"sidebar-lavender.css\"></a></li>\r\n");
      out.write("                            <li><a class=\"color-green\" href=\"javascript:;\" data-theme=\"sidebar-green.css\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"divider\"></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <label for=\"fixedheader\">Fixed Header</label>\r\n");
      out.write("                        <div id=\"fixedheader\" style=\"margin-top:5px;\"></div> \r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("<!--END TOPBAR-->\r\n");
      out.write("    <div id=\"page-container\">\r\n");
      out.write("        <!-- BEGIN SIDEBAR -->\r\n");
      out.write("        ");
      out.write("<nav id=\"page-leftbar\" role=\"navigation\">\r\n");
      out.write("                <!-- BEGIN SIDEBAR MENU -->\r\n");
      out.write("            <ul class=\"acc-menu\" id=\"sidebar\">\r\n");
      out.write("                <div><img class=\"img-responsive\" src=\"assets/img/BPS_LOGO.png\" title=\"Business Productivity Solution\"></div>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"DashboardOfficer\"><i class=\"fa fa-home\"></i> <span>Dashboard</span></a></li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-pencil-square-o\"></i> <span>Transaction</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelOrderOfficer\">Travel Orders</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"CashAdvanceOfficer\">Cash Advances</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelPlanOfficer\">Travel Plans</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"TravelExpenseOfficer\">Travel Expenses</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-book\"></i> <span>Report</span></a>\r\n");
      out.write("                    <ul class=\"acc-menu\">\r\n");
      out.write("                        <li><a href=\"TravelOrderReportOfficer\">Travel Order Report</a></li>\r\n");
      out.write("                        <li><a href=\"CashAdvanceReportOfficer\">Travel CashAdvance Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelPlanReportOfficer\">Travel Plan Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelBudgetReportOfficer\">Travel Budget Report</a></li>\r\n");
      out.write("                        <li><a href=\"TravelExpenseReportOfficer\">Travel Expense Report</a></li>\r\n");
      out.write("                        <!--li><a href=\"#\">Travel Analytical Report</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"acc-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"R-Expenseanalytical.jsp\">Expense Analytical Report</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"R-Travelanalytical.jsp\">Travel Analytical Report</a>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li-->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("               <!--li><a href=\"Messages.jsp\"><i class=\"fa fa-envelope\"></i><span>Messages</span></a></li-->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- END SIDEBAR MENU -->\r\n");
      out.write("        </nav>");
      out.write("\r\n");
      out.write("        <!-- END SIDEBAR -->\r\n");
      out.write("        <!-- BEGIN RIGHTBAR -->\r\n");
      out.write("        <!-- END RIGHTBAR -->\r\n");
      out.write("<div id=\"page-content\">\r\n");
      out.write("    <div id='wrap'>\r\n");
      out.write("        <div id=\"page-heading\">\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <li><a href=\"DashboardOfficer\">Dashboard</a></li>\r\n");
      out.write("                <li>Report</li>\r\n");
      out.write("                <li><b>Travel Plan</b></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!--BEGIN TABLE-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"panel panel-primary\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            <h4>Travel Plan List</h4>\r\n");
      out.write("                            <div class=\"options\">   \r\n");
      out.write("                    \r\n");
      out.write("                                <a href=\"javascript:;\" class=\"panel-collapse\"><i class=\"fa fa-chevron-down\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body collapse in\">\r\n");
      out.write("                           <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table table-striped table-bordered  table-hover datatables dataTable\" id=\"DataTables_Table_0\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                    <th>TO.#</th>\r\n");
      out.write("                                    <th>Personnel</th>\r\n");
      out.write("                                    <th>FromDate</th>\r\n");
      out.write("                                    <th>ToDate</th>\r\n");
      out.write("                                    <th>Destination</th>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<th>Total</th>\r\n");
      out.write("                                    <th>Status</th>\r\n");
      out.write("                                    <th>Approver</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                \r\n");
      out.write("                            <tbody>\r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("        <!--END TABLE-->\r\n");
      out.write("        </div> <!-- container -->\r\n");
      out.write("    </div> <!--wrap -->\r\n");
      out.write("</div> <!-- page-content -->\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<footer role=\"contentinfo\">\r\n");
      out.write("        <div class=\"clearfix\">\r\n");
      out.write("            <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                <li>BPS | Personnel Travel Management System &copy; ");
      out.print( new java.text.SimpleDateFormat("yyyy").format(new java.util.Date()) );
      out.write("</li>\r\n");
      out.write("                <button class=\"pull-right btn btn-inverse-alt btn-xs hidden-print\" id=\"back-to-top\"><i class=\"fa fa-arrow-up\"></i></button>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div> <!-- page-container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript' src='assets/js/jquery-1.10.2.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/jqueryui-1.10.3.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/bootstrap.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/enquire.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/jquery.cookie.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/jquery.nicescroll.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/codeprettifier/prettify.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/easypiechart/jquery.easypiechart.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/sparklines/jquery.sparklines.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/form-toggle/toggle.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/datatables/jquery.dataTables.min.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/plugins/datatables/dataTables.bootstrap.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/data-table.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/placeholdr.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/js/application.js'></script> \r\n");
      out.write("<script type='text/javascript' src='assets/demo/demo.js'></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /R-TravelplanOfficer.jsp(78,29) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/R-TravelplanOfficer.jsp(78,29) '${planlistreport}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${planlistreport}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /R-TravelplanOfficer.jsp(78,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("list");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <tr>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.tono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.fromdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.todate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.destination}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("                                        <td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("                                        <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.officername}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                        <td><a href=\"_ReportTravelPlan?tono=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.tono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("&tpid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"btn btn-default btn-xs\" target=\"_blank\">Preview</a></td>\r\n");
          out.write("                                    </tr>\r\n");
          out.write("                             ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /R-TravelplanOfficer.jsp(85,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.svtotal}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /R-TravelplanOfficer.jsp(85,14) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
    // /R-TravelplanOfficer.jsp(85,14) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setCurrencySymbol("P");
    // /R-TravelplanOfficer.jsp(85,14) name = minFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setMinFractionDigits(2);
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fminFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /R-TravelplanOfficer.jsp(88,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.status == 'Approved'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"label label-success\">Approved</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /R-TravelplanOfficer.jsp(91,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.status == 'Pending'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"label label-warning\">Pending</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"label label-danger\">Not Approved</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
